name: Upload Website to S3
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: ionic build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_S3_PUSHER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_S3_PUSHER_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/dev/deploy/showcase/access-key = AWS_ACCESS_KEY_ID,
            /dev/deploy/showcase/secret-access-key = AWS_SECRET_ACCESS_KEY,
            /dev/deploy/showcase/s3-bucket-name = AWS_S3_BUCKET,
            /dev/deploy/showcase/cloudfront-distribution-id = DISTRIBUTION_ID'
          withDecryption: 'true' # defaults to true

      - uses: TimekillerTK/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_REGION: us-east-2
          SOURCE_DIR: 'build'
