name: Upload Website to S3
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        env:
          REACT_APP_SERVER_URL: https://db-api.dev.lab.eten.bible:3012/v1/graphql
          REACT_APP_DATABASE_API_URL: https://db-api.dev.lab.eten.bible:3001
          # REACT_APP_AUTH_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6InB1YmxpYzoyMzIyM2JiNi1lODQ3LTRhMTAtOThhNS02Yzk1YjZlYWUxOGEiLCJ0eXAiOiJKV1QifQ.eyJhbGxvd2VkX3NjaGVtYXMiOltdLCJhbGxvd2VkX3RhYmxlcyI6e30sImF0X2hhc2giOiJGck5iNndKT1hmSDluTVZBamdWaGV3IiwiYXVkIjpbIjIyYWYzZmYzLTQ0MTAtNDhiZS1iN2JlLTI4NTYwZjIyOThhN19jb25zb2xlIl0sImF1dGhfdGltZSI6MTY2MzcyMTY0NiwiY29sbGFib3JhdG9yX3ByaXZpbGVnZXMiOlsiZ3JhcGhxbF9hZG1pbiJdLCJleHAiOjE2NjM3NTAyNTMsImlhdCI6MTY2Mzc0NjY1MywiaXNzIjoiaHR0cHM6Ly9vYXV0aC5wcm8uaGFzdXJhLmlvLyIsImp0aSI6ImRhZTJmZDJiLWRjN2QtNGIwMC04YTRiLTllZTE5ZTc5NTgxMCIsIm1ldHJpY3NfZnFkbiI6InVzLXdlc3QtMS1hd3MubWV0cmljcy5wcm8uaGFzdXJhLmlvIiwibm9uY2UiOiIiLCJwcm9qZWN0Ijp7ImlkIjoiMjJhZjNmZjMtNDQxMC00OGJlLWI3YmUtMjg1NjBmMjI5OGE3IiwibmFtZSI6ImZhc3QtaGVyb24tMzQifSwicmF0IjoxNjYzNzIxNjQyLCJzaWQiOiI2YWY4NDBmNi1lMGUwLTRiZDQtYmI1Ni1lN2I1N2I4MDM0ZjYiLCJzdWIiOiIxM2IxNGNiMi0wZWQzLTRkMmMtYmE2Ni1iNWFiMzVjMjM5YjcifQ.JEeWvc0m6U7cnXhM0VTuVpUq40V5lxlLsiOdcZUg3cmQIrPkEozSX4WuX3LNBPzJbiXw2JsIMXELY2X_tNH2XsVULwj-ZguAd6mHvaFAFwh4PZcbF9mqdzsxjDvq4j8_6Ysn0gFdcYbw8lwj6okgdjIKddIJFyuhp3iGf5wO8epX7x0yV4OQG7ByYTVlJmifVmjV0Y_OQo1fi7Vc6lxIA9_NClqK1FGx-VJeTu22Ojbb3WoMYgjuUCs81yI2idRSYgWZFox40RegHRU1DRIJ1ORVcjnde-ZFxF-W6wnknFKuN3tEHoncmW674jt_L4tg_DJHzTjnhVed-x9lgYCX4qjDMEWHc8MAbqDkIhCKnkopOH_0hWoVvsfSt_tyVZl3BtWx03mQBDyaZJD09YZaZDcDeeRrPvVHcvte10ABW1sJkFcB_MKMS7zurm-XIoXQppGXzDtq0JAEw7VzquWb1clEyxda_mCMAgqp4N1vL8W4fziqKNffnPtLrMZnBCix6lKAXliuebiUbMXbsNU4Vs5TvU8liCDiCMrYqJbzWJ8iWKOmdI--EFU8Vwes-EidJEigAKCREjZFNVknsdcxIJj4jDz2M8wIyTfEUfHpoMpbFXnMaIf1TKbB4ssb3bePHuDP75_IRu8PN89ufoyrK1KK2cimvlTkZV8D3GuGGEc
          REACT_APP_KEYCLOAK_URL: https://keycloak.dev.lab.eten.bible
          REACT_APP_KEYCLOAK_REALM: showcase
          REACT_APP_KEYCLOAK_CLIENT_ID: showcase-auth
          # REACT_APP_DISCUSSION_SUBSCRIPTION_WS_API: ws://10.1.2.12:8212/graphql
          # REACT_APP_DISCUSSION_SUBSCRIPTION_API: http://discussion-api-devcontainer:80/graphql
          # REACT_APP_DISCUSSION_API: http://10.1.2.2:8202/graphql
          # REACT_APP_FILE_API: http://10.1.2.3:8203/graphql
          REACT_APP_AGGREGATION_API: https://db-api.dev.lab.eten.bible:3010/graphql
          # REACT_APP_GRAPHQL_MODE: aggregation # independant
          # REACT_APP_NOTIFICATION_API: https://db-api.dev.lab.eten.bible:3005/graphql
          # REACT_APP_NOTIFICATION_SUBSCRIPTION_WS_API: wss://db-api.dev.lab.eten.bible:3010/graphql
          # REACT_APP_NOTIFICATION_SUBSCRIPTION_API: wss://db-api.dev.lab.eten.bible:3010/graphql

        run: ionic build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_S3_PUSHER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_S3_PUSHER_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/dev/deploy/showcase/access-key = AWS_ACCESS_KEY_ID,
            /dev/deploy/showcase/secret-access-key = AWS_SECRET_ACCESS_KEY,
            /dev/deploy/showcase/s3-bucket-name = AWS_S3_BUCKET,
            /dev/deploy/showcase/cloudfront-distribution-id = DISTRIBUTION_ID'
          withDecryption: 'true' # defaults to true

      - uses: TimekillerTK/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_REGION: us-east-2
          SOURCE_DIR: 'build'
